FROM python:3.12-slim-bookworm@sha256:1aaa65a85fda306ffb8b910824d4e93bdce61e212c7e87168123ea3073b41a1a
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ffmpeg libreoffice poppler-utils tesseract-ocr tesseract-ocr-eng tesseract-ocr-tha \
 && rm -rf /var/lib/apt/lists/*
RUN useradd --uid 1000 --create-home arra
COPY deploy/private/file-ingestion /app
USER arra
WORKDIR /app
ENTRYPOINT ["python3"]
